//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Korduene.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Korduene.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Sdk=&quot;Microsoft.NET.Sdk&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;TargetFramework&gt;netcoreapp3.0&lt;/TargetFramework&gt;
        ///  &lt;/PropertyGroup&gt;
        ///&lt;/Project&gt;.
        /// </summary>
        internal static string LibraryProjContent {
            get {
                return ResourceManager.GetString("LibraryProjContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Configuration;
        ///using System.Data;
        ///using System.Linq;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///
        ///namespace {ProjectName}
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interaction logic for App.xaml
        ///    /// &lt;/summary&gt;
        ///    public partial class App : Application
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string WpfFileAppCs {
            get {
                return ResourceManager.GetString("WpfFileAppCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Application x:Class=&quot;{ProjectName}.App&quot;
        ///             xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///             xmlns:local=&quot;clr-namespace:{ProjectName}&quot;
        ///             StartupUri=&quot;MainWindow.xaml&quot;&gt;
        ///    &lt;Application.Resources&gt;
        ///         
        ///    &lt;/Application.Resources&gt;
        ///&lt;/Application&gt;
        ///.
        /// </summary>
        internal static string WpfFileAppXaml {
            get {
                return ResourceManager.GetString("WpfFileAppXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility
        ///Microsoft.CSharp
        ///Microsoft.CSharp.RuntimeBinder
        ///Microsoft.VisualBasic
        ///Microsoft.VisualBasic.CompilerServices
        ///Microsoft.Win32.SafeHandles
        ///System.Buffers
        ///System.Buffers.Binary
        ///System.Buffers.Text
        ///System.CodeDom
        ///System.CodeDom.Compiler
        ///System.Collections.Generic
        ///System.Collections.Immutable
        ///System.Collections.ObjectModel
        ///System.ComponentModel
        ///System.ComponentModel.DataAnnotations
        ///System.ComponentModel.DataAnnotations.Schema
        ///System.ComponentModel.Design
        ///System.ComponentModel.Desi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WpfFileIgnoredNamespaces {
            get {
                return ResourceManager.GetString("WpfFileIgnoredNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace {ProjectName}
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interaction logic for MainWindow.xaml
        ///    /// &lt;/summary&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WpfFileMainWindowCs {
            get {
                return ResourceManager.GetString("WpfFileMainWindowCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.ComponentModel;
        ///using System.Diagnostics;
        ///using System.Runtime.CompilerServices;
        ///using System.Text;
        ///using System.Windows.Input;
        ///
        ///namespace {ProjectName}
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Main Window ViewModel
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;INotifyPropertyChanged&quot; /&gt;
        ///    [Description(&quot;Main Window ViewModel&quot;)]
        ///    [DisplayName(&quot;MainWindowViewModel&quot;)]
        ///    [DebuggerDisplay(&quot;{this}&quot;)]
        ///    pub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WpfFileMainWindowViewModelCs {
            get {
                return ResourceManager.GetString("WpfFileMainWindowViewModelCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Window x:Class=&quot;{ProjectName}.MainWindow&quot;
        ///        xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///        xmlns:local=&quot;clr-namespace:{ProjectName}&quot;
        ///        mc:Ignorable=&quot;d&quot;
        ///        Title=&quot;MainWindow&quot; Height=&quot;450&quot; Width=&quot;800&quot;&gt;
        ///    &lt;Grid&gt;
        ///
        ///    &lt;/Grid&gt;
        ///&lt;/Window&gt;
        ///.
        /// </summary>
        internal static string WpfFileMainWindowXaml {
            get {
                return ResourceManager.GetString("WpfFileMainWindowXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Sdk=&quot;Microsoft.NET.Sdk.WindowsDesktop&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputType&gt;
        ///    &lt;TargetFramework&gt;netcoreapp3.0&lt;/TargetFramework&gt;
        ///    &lt;UseWPF&gt;true&lt;/UseWPF&gt;
        ///  &lt;/PropertyGroup&gt;
        ///&lt;/Project&gt;.
        /// </summary>
        internal static string WpfProjContent {
            get {
                return ResourceManager.GetString("WpfProjContent", resourceCulture);
            }
        }
    }
}
